version: '3.8'

services:
  backend:
    build:
      context: ./backend
    image : backend
    depends_on:
      - db
    secrets:
      - db-password
    expose:
      - "8000" 

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-password
      MYSQL_DATABASE: example
    volumes:
      - db_data:/var/lib/mysql
    secrets:
      - db-password

  proxy:
    build: nginx/
    image: nginx_proxy
    ports:
      - "443:443"
    volumes:
      - /etc/nginx/ssl/:/etc/nginx/ssl/
    depends_on:
      - backend

secrets:
  db-password:
    file: ./db-password.txt

volumes:
  db_data:
